epic:
  epic-url: https://www.epicgames.com/store/en-US/
  driver-args:
    - "--blink-settings=imagesEnabled=false"
    - "--no-first-run"
    - "--disable-infobars"
    - "--disable-gpu"
    - "--no-default-browser-check"
  email: ${EMAIL}
  password: ${PASSWORD}
logging:
  level:
    com.hsn.epic4j: ${LOG_LEVEL:info}

