name: DailyClaim

on: 
  workflow_dispatch:
  release:
    types: [published]
  push:
    tags:
    - 'v*'
  #  branches: 
  #    - master
  schedule:
    - cron: "0 2 * * *"
  watch:
    types: [started]
   
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id  # 自己点的 start
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Set up Python #安装python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install Environment
      run: |
        sudo apt-get remove docker docker-engine docker.io containerd runc -y
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
        sudo apt-get update
        sudo apt-get install docker-ce docker-ce-cli containerd.io -y
        docker pull huisunan/epic4j:latest
    # sudo apt install openjdk-8-jre -y
    - name: Run script
      env:
        config: ${{ secrets.config }}
      shell: python
      run: |
        import os
        import json
        config = json.loads(os.environ.get('config'))
        username = config['username']
        password = config['password']
        for i in (len(username)):
            os.system(f'docker run -d -e EMAIL={username[i]} -e PASSWORD={password[i]} -e LOG_LEVEL=debug --name epic4j huisunan/epic4j:latest')
